#############################################################################
# Makefile for building: CGViewer.app/Contents/MacOS/CGViewer
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  CGViewer.pro
# Template: app
# Command: /Users/mirco/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CGViewer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt/5.4/clang_64/mkspecs/macx-clang -I. -I../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/mirco/Qt/5.4/clang_64/lib
QMAKE         = /Users/mirco/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CGViewer1.0.0
DISTDIR = /Users/mirco/Studium/Bachelor/Computergrafik/CGViewer\ pure/obj/CGViewer1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/mirco/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/mirco/Qt/5.4/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/Mainwindow.cpp \
		src/Scene.cpp \
		src/EditWidgets.cpp \
		src/Model.cpp \
		src/Light.cpp moc/moc_Mainwindow.cpp \
		moc/moc_Scene.cpp \
		moc/moc_EditWidgets.cpp
OBJECTS       = obj/main.o \
		obj/Mainwindow.o \
		obj/Scene.o \
		obj/EditWidgets.o \
		obj/Model.o \
		obj/Light.o \
		obj/moc_Mainwindow.o \
		obj/moc_Scene.o \
		obj/moc_EditWidgets.o
DIST          = ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		CGViewer.pro src/Mainwindow.h \
		src/CGTypes.h \
		src/Scene.h \
		src/EditWidgets.h \
		src/Model.h \
		src/Light.h \
		src/CGFunctions.h src/main.cpp \
		src/Mainwindow.cpp \
		src/Scene.cpp \
		src/EditWidgets.cpp \
		src/Model.cpp \
		src/Light.cpp
QMAKE_TARGET  = CGViewer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = CGViewer.app/Contents/MacOS/CGViewer

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d CGViewer.app/Contents/MacOS/ || mkdir -p CGViewer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CGViewer.pro ../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		CGViewer.pro \
		/Users/mirco/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/mirco/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/mirco/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/mirco/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CGViewer.pro
../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
CGViewer.pro:
/Users/mirco/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/mirco/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/mirco/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/mirco/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CGViewer.pro

qmake_all: FORCE

CGViewer.app/Contents/PkgInfo: 
	@test -d CGViewer.app/Contents || mkdir -p CGViewer.app/Contents
	@$(DEL_FILE) CGViewer.app/Contents/PkgInfo
	@echo "APPL????" >CGViewer.app/Contents/PkgInfo
CGViewer.app/Contents/Resources/empty.lproj: 
	@test -d CGViewer.app/Contents/Resources || mkdir -p CGViewer.app/Contents/Resources
	@touch CGViewer.app/Contents/Resources/empty.lproj
	
CGViewer.app/Contents/Info.plist: 
	@test -d CGViewer.app/Contents || mkdir -p CGViewer.app/Contents
	@$(DEL_FILE) CGViewer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,au.edu.uow.CGViewer,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,CGViewer,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >CGViewer.app/Contents/Info.plist

all: Makefile \
		CGViewer.app/Contents/PkgInfo \
		CGViewer.app/Contents/Resources/empty.lproj \
		CGViewer.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/Mainwindow.h src/CGTypes.h src/Scene.h src/EditWidgets.h src/Model.h src/Light.h src/CGFunctions.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Mainwindow.cpp src/Scene.cpp src/EditWidgets.cpp src/Model.cpp src/Light.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CGViewer.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_Mainwindow.cpp moc/moc_Scene.cpp moc/moc_EditWidgets.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_Mainwindow.cpp moc/moc_Scene.cpp moc/moc_EditWidgets.cpp
moc/moc_Mainwindow.cpp: ../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/Mainwindow.h
	/Users/mirco/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/mirco/Qt/5.4/clang_64/mkspecs/macx-clang -I'/Users/mirco/Studium/Bachelor/Computergrafik/CGViewer pure' -I/Users/mirco/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/mirco/Qt/5.4/clang_64/lib src/Mainwindow.h -o moc/moc_Mainwindow.cpp

moc/moc_Scene.cpp: ../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFramebufferObject \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglframebufferobject.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector4D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QWheelEvent \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		src/Scene.h
	/Users/mirco/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/mirco/Qt/5.4/clang_64/mkspecs/macx-clang -I'/Users/mirco/Studium/Bachelor/Computergrafik/CGViewer pure' -I/Users/mirco/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/mirco/Qt/5.4/clang_64/lib src/Scene.h -o moc/moc_Scene.cpp

moc/moc_EditWidgets.cpp: ../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		src/EditWidgets.h
	/Users/mirco/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/mirco/Qt/5.4/clang_64/mkspecs/macx-clang -I'/Users/mirco/Studium/Bachelor/Computergrafik/CGViewer pure' -I/Users/mirco/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/mirco/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/mirco/Qt/5.4/clang_64/lib src/EditWidgets.h -o moc/moc_EditWidgets.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp src/Mainwindow.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFormat \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Mainwindow.o: src/Mainwindow.cpp ../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStatusBar \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		src/Mainwindow.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/Scene.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFramebufferObject \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglframebufferobject.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector4D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QWheelEvent \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		src/EditWidgets.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mainwindow.o src/Mainwindow.cpp

obj/Scene.o: src/Scene.cpp ../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		src/Scene.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFramebufferObject \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglframebufferobject.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector4D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QWheelEvent \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		src/Model.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector3D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMatrix4x4 \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLBuffer \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglbuffer.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFunctions \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglfunctions.h \
		src/CGTypes.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		src/Light.h \
		src/EditWidgets.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		src/CGFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Scene.o src/Scene.cpp

obj/EditWidgets.o: src/EditWidgets.cpp src/EditWidgets.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QDoubleValidator \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		src/Light.h \
		src/Model.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector3D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMatrix4x4 \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLBuffer \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglbuffer.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFunctions \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglfunctions.h \
		src/CGTypes.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EditWidgets.o src/EditWidgets.cpp

obj/Model.o: src/Model.cpp ../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		src/Model.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector3D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMatrix4x4 \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLBuffer \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglbuffer.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFunctions \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglfunctions.h \
		src/CGTypes.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Model.o src/Model.cpp

obj/Light.o: src/Light.cpp src/Light.h \
		src/Model.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector3D \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMatrix4x4 \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLBuffer \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglbuffer.h \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLFunctions \
		../../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qglfunctions.h \
		src/CGTypes.h \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Light.o src/Light.cpp

obj/moc_Mainwindow.o: moc/moc_Mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Mainwindow.o moc/moc_Mainwindow.cpp

obj/moc_Scene.o: moc/moc_Scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Scene.o moc/moc_Scene.cpp

obj/moc_EditWidgets.o: moc/moc_EditWidgets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EditWidgets.o moc/moc_EditWidgets.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

